rps_game:
- method:
  - segment_type: "2d_camera"
    output_topic_types:
      # - /usb_cam/image_raw
      - camera_data
  - segment_type: "openpose"
    input_topic_types:
      # - /usb_cam/image_raw
      - camera_data
    output_topic_types:
      # - /frame
      - keypoints
  - segment_type: "gesture_classifier"
    input_topic_types:
      - keypoints
    output_topic_types:
      - gestures

  # - segment_type: "cs_test_2"
  #   input_topic_types:
  #     - data_type_2
  #     - data_type_3
  #   output_topic_types:
  #     - data_type_4
  #     - data_type_5#

# tests:
# - method:
#   - segment_type: "cs_test_0"
#     output_topic_types:
#       - data_type_0
#       - data_type_1

#   - segment_type: "cs_test_1"
#     input_topic_types:
#       - data_type_0
#       - data_type_1
#     output_topic_types:
#       - data_type_2
#       - data_type_3

#   - segment_type: "cs_test_2"
#     input_topic_types:
#       - data_type_2
#       - data_type_3
#     output_topic_types:
#       - data_type_4
#       - data_type_5